#!/bin/bash
set -euo pipefail

APP_DIR="/usr/share/nextcloud/apps/recognize"
SRC_DIR="$(cd "$(dirname "$0")" && pwd)"
OCC="php /usr/share/nextcloud/occ"
PYTHON_BIN="/home/aladjidi/mambaforge/envs/313/bin/python"

echo "=== Stopping recognize service ==="
systemctl stop recognize.service 2>/dev/null || true
pkill -f 'python.*service\.py' || true
pkill -f 'php /usr/share/nextcloud/occ recognize:classify' || true
sleep 1
echo "Done"

echo "=== Deploying Python service files ==="
mkdir -p "$APP_DIR/python/classifiers" "$APP_DIR/python/data"

# Core service files
for f in service.py pipeline.py config.py db.py nc_api.py clustering.py \
         gpu_setup.py rules_engine.py setup_config.py \
         recognize.service.template; do
    [ -f "$SRC_DIR/python/$f" ] && cp -v "$SRC_DIR/python/$f" "$APP_DIR/python/"
done

# Classifier modules
for f in __init__.py base.py imagenet.py faces.py landmarks.py movinet.py musicnn.py; do
    [ -f "$SRC_DIR/python/classifiers/$f" ] && cp -v "$SRC_DIR/python/classifiers/$f" "$APP_DIR/python/classifiers/"
done

# Data files
for f in yamnet_class_map.csv; do
    [ -f "$SRC_DIR/python/data/$f" ] && cp -v "$SRC_DIR/python/data/$f" "$APP_DIR/python/data/"
done

# Config (if exists — generated by setup_config.py)
[ -f "$SRC_DIR/python/nc_config.json" ] && cp -v "$SRC_DIR/python/nc_config.json" "$APP_DIR/python/"

echo "Done"

echo "=== Deploying PHP files ==="
cp -v "$SRC_DIR"/lib/Controller/InternalController.php "$APP_DIR/lib/Controller/"
cp -v "$SRC_DIR"/lib/Migration/Version011000003Date20260308094821.php "$APP_DIR/lib/Migration/"
cp -v "$SRC_DIR"/appinfo/routes.php "$APP_DIR/appinfo/"
# Keep deploying existing modified files
cp -v "$SRC_DIR"/lib/Classifiers/Classifier.php "$APP_DIR/lib/Classifiers/"
cp -v "$SRC_DIR"/lib/Command/Classify.php "$APP_DIR/lib/Command/"
echo "Done"

echo "=== Running migrations ==="
sudo -u apache $OCC maintenance:repair --include-expensive || true
echo "Done"

# Ensure apache owns everything
chown -R apache:apache "$APP_DIR/python/" "$APP_DIR/lib/" "$APP_DIR/appinfo/"

echo "=== Setup instructions ==="
echo ""
echo "1. Generate config + systemd service:"
echo "   sudo $PYTHON_BIN $APP_DIR/python/setup_config.py"
echo ""
echo "2. Install and start the service:"
echo "   sudo cp $APP_DIR/python/recognize.service /etc/systemd/system/"
echo "   sudo systemctl daemon-reload"
echo "   sudo systemctl enable --now recognize"
echo ""
echo "3. Check status:"
echo "   sudo systemctl status recognize"
echo "   sudo journalctl -u recognize -f"
